### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'/openedx/data/uploads/user_tasks/2018/03/22/course.QQQZen.tar.gz'

### ISSUE THREAD

**Issue by natea** [regisb/openedx-docker#14]
When I try to export a course, I get this error. I'm guessing this is because the directory `/openedx/data/uploads/user_tasks` has not been created?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/common/djangoapps/util/views.py", line 49, in inner
    response = view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 426, in export_output_handler
    tarball = course_import_export_storage.open(artifact.file.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 37, in open
    return self._open(name, mode)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 201, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/openedx/data/uploads/user_tasks/2018/03/22/course.QQQZen.tar.gz'
2018-03-22 00:48:17,688 ERROR 1485 [django.request] base.py:256 - Internal Server Error: /export_output/course-v1:Appsembler+OS101+2018_Winter
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/common/djangoapps/util/views.py", line 49, in inner
    response = view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 426, in export_output_handler
    tarball = course_import_export_storage.open(artifact.file.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 37, in open
    return self._open(name, mode)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 201, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/openedx/data/uploads/user_tasks/2018/03/22/course.QQQZen.tar.gz'
```

**Comment by regisb** [comment]
Hmmmm I'm not sure about that. Does the error go away when you create the `user_tasks` folder in `data/uploads`?

**Comment by natea** [comment]
In the `openedxdocker_cms_1` container, I only see a directory `/openedx/data/uploads` and inside that directory, I added a `user_tasks` folder. 

I don't see a folder called `data/cms/uploads`.

**Comment by regisb** [comment]
The `data/cms/` folder should exist on the hosts and is mapped to `/openedx/data/` on the container, so it's fine if you created the folder in the container.
Did it solve the problem?

**Comment by AbdulZor** [comment]
I am getting a similar problem. I am new to Open edx and tutor. I have installed Open edx with kubernetes. Because I am on a windows machine I work with WSL.

I have tried making a `user_tasks` folder, but it did solve the problem.

When I try to export a course I get this error: 
current dir: `/openedx/data/logs`, command: `cat all.log`
`
2020-02-17 09:47:21,864 ERROR 10 [root] signals.py:21 - Uncaught exception from None
Traceback (most recent call last):
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/common/djangoapps/util/views.py", line 49, in inner
    response = view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 427, in export_output_handler
    tarball = course_import_export_storage.open(artifact.file.name)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/openedx/media/user_tasks/2020/02/17/course.BD4E4d.tar.gz'
2020-02-17 09:47:21,865 ERROR 10 [django.request] exception.py:135 - Internal Server Error: /export_output/course-v1:OrganizationAbdul+AZ101+2020_B1
Traceback (most recent call last):
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/common/djangoapps/util/views.py", line 49, in inner
    response = view_func(request, *args, **kwargs)
  File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 427, in export_output_handler
    tarball = course_import_export_storage.open(artifact.file.name)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/openedx/media/user_tasks/2020/02/17/course.BD4E4d.tar.gz'
2020-02-17 09:47:23,210 INFO 12 [tracking] logger.py:50 - {"username": "adminzor", "event_type": "/export/course-v1:OrganizationAbdul+AZ101+2020_B1",
`

and with `tutor k8s logs cms` I get:
`File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/openedx/media/user_tasks/2020/02/17/course.BD4E4d.tar.gz' `

**Comment by natea** [comment]
do you have a file named "course.BD4E4d.tar.gz" in the directory
"/openedx/media/user_tasks/2020/02/17/" ?

/openedx/media/user_tasks/2020/02/17/course.BD4E4d.tar.gz

that's what it's complaining about in the error message.


On Mon, Feb 17, 2020 at 5:05 AM AbdulZor <notifications@github.com> wrote:
>
> I am getting a similar problem. I am new to Open edx and tutor. I have installed Open edx with kubernetes. Because I am on a windows machine I work with WSL.
>
> I have tried making a user_tasks folder, but it did solve the problem.
>
> When I try to export a course I get this error:
> current dir: /openedx/data/logs, command: cat all.log
> 2020-02-17 09:47:21,864 ERROR 10 [root] signals.py:21 - Uncaught exception from None Traceback (most recent call last): File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner response = get_response(request) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response response = self._get_response(request) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response response = self.process_exception_by_middleware(e, request) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/openedx/venv/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner return func(request, *args, **kwargs) File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view response = view_func(request, *args, **kwargs) File "/openedx/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view return view_func(request, *args, **kwargs) File "/openedx/edx-platform/common/djangoapps/util/views.py", line 49, in inner response = view_func(request, *args, **kwargs) File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 427, in export_output_handler tarball = course_import_export_storage.open(artifact.file.name) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open return self._open(name, mode) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open return File(open(self.path(name), mode)) IOError: [Errno 2] No such file or directory: u'/openedx/media/user_tasks/2020/02/17/course.BD4E4d.tar.gz' 2020-02-17 09:47:21,865 ERROR 10 [django.request] exception.py:135 - Internal Server Error: /export_output/course-v1:OrganizationAbdul+AZ101+2020_B1 Traceback (most recent call last): File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner response = get_response(request) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response response = self._get_response(request) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response response = self.process_exception_by_middleware(e, request) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/openedx/venv/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner return func(request, *args, **kwargs) File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view response = view_func(request, *args, **kwargs) File "/openedx/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view return view_func(request, *args, **kwargs) File "/openedx/edx-platform/common/djangoapps/util/views.py", line 49, in inner response = view_func(request, *args, **kwargs) File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 427, in export_output_handler tarball = course_import_export_storage.open(artifact.file.name) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open return self._open(name, mode) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open return File(open(self.path(name), mode)) IOError: [Errno 2] No such file or directory: u'/openedx/media/user_tasks/2020/02/17/course.BD4E4d.tar.gz' 2020-02-17 09:47:23,210 INFO 12 [tracking] logger.py:50 - {"username": "adminzor", "event_type": "/export/course-v1:OrganizationAbdul+AZ101+2020_B1",
>
> and with tutor k8s logs cms I get:
> File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open return self._open(name, mode) File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open return File(open(self.path(name), mode)) IOError: [Errno 2] No such file or directory: u'/openedx/media/user_tasks/2020/02/17/course.BD4E4d.tar.gz'
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 


Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by AbdulZor** [comment]
I did not have the directory "user_tasks/2020/02/17/", but after `tutor k8s quickstart`, the error went away and I got another error [issue](https://github.com/overhangio/tutor/issues/294#issue-566352240). Thank you for your reply.
