### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'XModule' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by natea** [regisb/openedx-docker#23]
When I run the update_assets command in the developer environment, I get the following error:

```
$ paver update_assets lms --settings=development
...
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "/usr/local/bin/xmodule_assets", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3125, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'XModule' distribution was not found and is required by the application


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "https://registry.npmjs.org/" || (echo setting registry; npm config set registry https://registry.npmjs.org/)
npm install
xmodule_assets common/static/xmodule

Build failed running pavelib.assets.update_assets: Subprocess return code: 1
```

**Comment by regisb** [comment]
This happens when you mount an `edx-platform` folder from the host, right? The fix should be pretty straightforward: just run `pip install -r requirements/edx/local.txt`.

Now for the explanation: the `pip` command generates files inside the edx-platform folder which are necessary to find (among others) the XModule package. During build these files are generated for the edx-platform inside the container, but not for the edx-platform from the host, because volumes are only mounted at runtime, not during build.

**Comment by natea** [comment]
That seemed to fix the problem, but are you saying that every time I run the `make lms` command, I'm going to have to re-run `pip install -r requirements/edx/local.txt`?

**Comment by regisb** [comment]
No, you just have to run it once to generate the required files in the edx-platform folder from the host.
