### ISSUE TITLE
ImportError: No module named universal.production

### ISSUE THREAD

**Issue by macagua** [regisb/openedx-docker#28]
Hi @regisb 

I have the following error: 

```bash
ubuntu@ip-172-30-4-230:~/openedx-docker$ make all
./configure
Your website domain name for students (LMS) (default: "http://lms.kimetrics.com"): 
Your website domain name for teachers (CMS) (default: "http://studio.kimetrics.com"): 
Secret key -- if you don't know what this is, you can safely accept the default (default: "********"): 
Platform name/title (default: "Kimetrics - Smart field management - Cursos en linea"): 
MySQL database name (default: "openedx"): 
MySQL database username (default: "openedx"): 
MySQL database password (default: "password"): 
MongoDb database name (default: "openedx"): 

Configuration values were saved to  config/openedx/config.json
Generated config file config/openedx/lms.env.json (from template config/openedx/templates/lms.env.json.templ)
Generated config file config/openedx/cms.env.json (from template config/openedx/templates/cms.env.json.templ)
Generated config file config/openedx/lms.auth.json (from template config/openedx/templates/lms.auth.json.templ)
Generated config file config/openedx/cms.auth.json (from template config/openedx/templates/cms.auth.json.templ)
Generated config file mysql/config/username (from template mysql/config/templates/username.templ)
Generated config file mysql/config/password (from template mysql/config/templates/password.templ)
Generated config file mysql/config/database (from template mysql/config/templates/database.templ)
Generated config file config/nginx/lms.conf (from template config/nginx/templates/lms.conf.templ)
Generated config file config/nginx/cms.conf (from template config/nginx/templates/cms.conf.templ)

Configuration files were successfuly generated. You may now run the app containers.
docker-compose pull
Pulling memcached  ... done
Pulling mongodb    ... done
Pulling mysql      ... done
Pulling nginx      ... done
Pulling rabbitmq   ... done
Pulling smtp       ... done
Pulling lms        ... done
Pulling cms        ... done
Pulling lms_worker ... done
Pulling cms_worker ... done
docker-compose run --rm -e USERID=$(id -u) -e SETTINGS=universal.production lms bash -c "wait-for-greenlight.sh && ./manage.py lms migrate"
Starting openedx-docker_memcached_1 ... done
Starting openedx-docker_smtp_1      ... done
Starting openedx-docker_mysql_1     ... done
Starting openedx-docker_rabbitmq_1  ... done
Starting openedx-docker_mongodb_1   ... done
creating new user 'openedx' with UID 1000
Checking system...
2018-05-23 19:40:11,824 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/openassessment/workflow/models.py:46: RemovedInDjango19Warning: Model class openassessment.workflow.models.AssessmentWorkflow doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class AssessmentWorkflow(TimeStampedModel, StatusModel):

2018-05-23 19:40:11,827 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/openassessment/workflow/models.py:608: RemovedInDjango19Warning: Model class openassessment.workflow.models.AssessmentWorkflowStep doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class AssessmentWorkflowStep(models.Model):

2018-05-23 19:40:11,828 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/openassessment/workflow/models.py:749: RemovedInDjango19Warning: Model class openassessment.workflow.models.AssessmentWorkflowCancellation doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class AssessmentWorkflowCancellation(models.Model):

2018-05-23 19:40:12,097 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:52: RemovedInDjango19Warning: Model class edxval.models.Profile doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Profile(models.Model):

2018-05-23 19:40:12,098 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:75: RemovedInDjango19Warning: Model class edxval.models.Video doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Video(models.Model):

2018-05-23 19:40:12,099 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:123: RemovedInDjango19Warning: Model class edxval.models.CourseVideo doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CourseVideo(models.Model, ModelFactoryWithValidation):

2018-05-23 19:40:12,100 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:144: RemovedInDjango19Warning: Model class edxval.models.EncodedVideo doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class EncodedVideo(models.Model):

2018-05-23 19:40:12,101 WARNING 12 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:164: RemovedInDjango19Warning: Model class edxval.models.Subtitle doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Subtitle(models.Model):

2018-05-23 19:40:12,111 WARNING 12 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/video_config/models.py:10: RemovedInDjango19Warning: Model class openedx.core.djangoapps.video_config.models.HLSPlaybackEnabledFlag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class HLSPlaybackEnabledFlag(ConfigurationModel):

2018-05-23 19:40:12,113 WARNING 12 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/video_config/models.py:51: RemovedInDjango19Warning: Model class openedx.core.djangoapps.video_config.models.CourseHLSPlaybackEnabledFlag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CourseHLSPlaybackEnabledFlag(ConfigurationModel):

2018-05-23 19:40:13,196 WARNING 12 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/bookmarks/models.py:41: RemovedInDjango19Warning: Model class openedx.core.djangoapps.bookmarks.models.Bookmark doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Bookmark(TimeStampedModel):

2018-05-23 19:40:13,204 WARNING 12 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/bookmarks/models.py:186: RemovedInDjango19Warning: Model class openedx.core.djangoapps.bookmarks.models.XBlockCache doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class XBlockCache(TimeStampedModel):

2018-05-23 19:40:14,160 INFO 12 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
System check identified no issues (0 silenced).

System is ready \o/
2018-05-23 19:40:17,355 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/openassessment/workflow/models.py:46: RemovedInDjango19Warning: Model class openassessment.workflow.models.AssessmentWorkflow doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class AssessmentWorkflow(TimeStampedModel, StatusModel):

2018-05-23 19:40:17,357 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/openassessment/workflow/models.py:608: RemovedInDjango19Warning: Model class openassessment.workflow.models.AssessmentWorkflowStep doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class AssessmentWorkflowStep(models.Model):

2018-05-23 19:40:17,358 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/openassessment/workflow/models.py:749: RemovedInDjango19Warning: Model class openassessment.workflow.models.AssessmentWorkflowCancellation doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class AssessmentWorkflowCancellation(models.Model):

2018-05-23 19:40:17,445 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:52: RemovedInDjango19Warning: Model class edxval.models.Profile doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Profile(models.Model):

2018-05-23 19:40:17,446 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:75: RemovedInDjango19Warning: Model class edxval.models.Video doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Video(models.Model):

2018-05-23 19:40:17,447 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:123: RemovedInDjango19Warning: Model class edxval.models.CourseVideo doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CourseVideo(models.Model, ModelFactoryWithValidation):

2018-05-23 19:40:17,448 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:144: RemovedInDjango19Warning: Model class edxval.models.EncodedVideo doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class EncodedVideo(models.Model):

2018-05-23 19:40:17,449 WARNING 131 [py.warnings] base.py:116 - /usr/local/lib/python2.7/dist-packages/edxval/models.py:164: RemovedInDjango19Warning: Model class edxval.models.Subtitle doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Subtitle(models.Model):

2018-05-23 19:40:17,453 WARNING 131 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/video_config/models.py:10: RemovedInDjango19Warning: Model class openedx.core.djangoapps.video_config.models.HLSPlaybackEnabledFlag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class HLSPlaybackEnabledFlag(ConfigurationModel):

2018-05-23 19:40:17,454 WARNING 131 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/video_config/models.py:51: RemovedInDjango19Warning: Model class openedx.core.djangoapps.video_config.models.CourseHLSPlaybackEnabledFlag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CourseHLSPlaybackEnabledFlag(ConfigurationModel):

2018-05-23 19:40:18,332 WARNING 131 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/bookmarks/models.py:41: RemovedInDjango19Warning: Model class openedx.core.djangoapps.bookmarks.models.Bookmark doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Bookmark(TimeStampedModel):

2018-05-23 19:40:18,334 WARNING 131 [py.warnings] base.py:116 - /openedx/edx-platform/openedx/core/djangoapps/bookmarks/models.py:186: RemovedInDjango19Warning: Model class openedx.core.djangoapps.bookmarks.models.XBlockCache doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class XBlockCache(TimeStampedModel):

2018-05-23 19:40:18,947 INFO 131 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Operations to perform:
  Synchronize unmigrated apps: eventtracking_django, gating, links, webpack_loader, course_structure_api, release_util, discussion_api, learner_dashboard, edxnotes, django_sites_extensions, auth_exchange, service_status, web_fragments, coursegraph, sekizai, rest_framework, edxmako, openassessment, datadog, staticbook, common_views, course_wiki, edx_sga, support, enterprise_support, django_object_actions, django_countries, humanize, course_blocks, provider, notification_prefs, thumbnail, xblock, course_experience, mptt, notifier_api, staticfiles, markdownedx, fileupload, plugin_api, course_search, edx_jsme, monitoring, instructor, static_template_view, corsheaders, statici18n, pipeline, simple_history, enrollment, messages, config_models, django_extensions, dashboard, django_nose, debug, mailing, discussion, course_bookmarks
  Apply all migrations: wiki, status, dark_lang, student, video_config, branding, user_api, django_comment_common, redirects, course_overviews, sites, experiments, grades, crawlers, lms_xblock, rss_proxy, bookmarks, waffle_utils, mobile_api, badges, course_groups, database_fixups, integrated_channel, course_modes, sessions, verified_track_content, shoppingcart, block_structure, external_auth, track, contenttypes, splash, workflow, certificates, static_replace, third_party_auth, assessment, sap_success_factors, submissions, oauth_dispatch, oauth2_provider, theming, instructor_task, organizations, edx_oauth2_provider, microsite_configuration, django_notify, celery_utils, api_admin, auth, util, verify_student, catalog, oauth2, site_configuration, social_django, credentials, email_marketing, contentserver, waffle, xblock_django, embargo, commerce, milestones, course_action_state, edx_proctoring, admin, oauth_provider, courseware, programs, djcelery, edxval, teams, credit, django_openid_auth, bulk_email, survey, course_structures, enterprise, cors_csrf, notes, self_paced
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
docker-compose run --rm -e USERID=$(id -u) -e SETTINGS=universal.production cms bash -c "wait-for-greenlight.sh && ./manage.py cms migrate"
Starting openedx-docker_memcached_1 ... done
Starting openedx-docker_smtp_1      ... done
Starting openedx-docker_mysql_1     ... done
Starting openedx-docker_rabbitmq_1  ... done
Starting openedx-docker_mongodb_1   ... done
creating new user 'openedx' with UID 1000
Checking system...
Traceback (most recent call last):
  File "./manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/cms/startup.py", line 11, in <module>
    from openedx.core.djangoapps.theming.core import enable_theming
  File "/openedx/edx-platform/openedx/core/djangoapps/theming/core.py", line 9, in <module>
    from .helpers import get_themes
  File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 9, in <module>
    from django.contrib.staticfiles.storage import staticfiles_storage
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/storage.py", line 12, in <module>
    from django.core.cache import (
  File "/usr/local/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named universal.production
.Traceback (most recent call last):
  File "./manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/cms/startup.py", line 11, in <module>
    from openedx.core.djangoapps.theming.core import enable_theming
  File "/openedx/edx-platform/openedx/core/djangoapps/theming/core.py", line 9, in <module>
    from .helpers import get_themes
  File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 9, in <module>
    from django.contrib.staticfiles.storage import staticfiles_storage
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/storage.py", line 12, in <module>
    from django.core.cache import (
  File "/usr/local/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named universal.production
```
Any idea about what Python library needed installed for fix the ImportError Exception?

**Comment by regisb** [comment]
The `universal.production` module is supposed to be in `config/openedx/universal/cms/production.py`, on the host. It contains the settings required to run the CMS and it should be mounted inside the docker image.

1. Which version of `openedx-docker` are you using? Please give the result of `git log -1` on the host.
2. Is the configuration volume properly mounted inside the container? Please run the following: `make cms` on the host, and then in the container give the result of all following commands:

```
ls -lh cms/envs/universal
ls -lh cms/envs/universal/
ls -lh /openedx/config/
ls -lh /openedx/config/universal/cms/
```

**Comment by macagua** [comment]
Hi @regisb 

Which version of openedx-docker are you using? 

```bash
$ git log -1
commit bfbc0c2b5bf244826a32014a8edbe1e6188b0f1d
Author: Régis Behmo <regis@behmo.com>
Date:   Wed May 16 19:35:18 2018 +0200

    Switch docker hub username
```

``make cms`` and container structure commands:

```bash
$ make cms
docker-compose run --rm -e USERID=$(id -u) -e SETTINGS=universal.production -p 8001:8001 cms bash
Starting openedx-docker_mysql_1     ... done
Starting openedx-docker_smtp_1      ... done
Starting openedx-docker_memcached_1 ... done
Starting openedx-docker_mysql_1     ... done
creating new user 'openedx' with UID 1000
openedx@272f23c7aafc:~/edx-platform$ ls                   
AUTHORS		  Makefile	     cms	  docs		openedx       pavement.py      screenshots  static	  webpack.config.js
CHANGELOG.rst	  Open_edX.egg-info  codecov.yml  lms		openedx.yaml  pylintrc	       scripts	    test_root
CONTRIBUTING.rst  README.rst	     common	  manage.py	package.json  pylintrc_tweaks  setup.cfg    themes
LICENSE		  circle.yml	     conf	  node_modules	pavelib       requirements     setup.py     vendor_extra
openedx@272f23c7aafc:~/edx-platform$ ls -lh cms/envs/universal
lrwxrwxrwx 1 openedx root 32 May 16 16:36 cms/envs/universal -> /openedx/config/universal/cms.py
openedx@272f23c7aafc:~/edx-platform$ ls -lh cms/envs/universal/
ls: cannot access 'cms/envs/universal/': No such file or directory
openedx@272f23c7aafc:~/edx-platform$ ls -lh /openedx/config/
total 28K
-rw-rw-r-- 1 openedx openedx  856 May 23 19:35 cms.auth.json
-rw-rw-r-- 1 openedx openedx 2.5K May 23 19:35 cms.env.json
-rw-rw-r-- 1 openedx openedx  358 May 23 19:35 config.json
-rw-rw-r-- 1 openedx openedx  856 May 23 19:35 lms.auth.json
-rw-rw-r-- 1 openedx openedx 2.5K May 23 19:35 lms.env.json
drwxrwxr-x 2 openedx openedx 4.0K May 23 04:14 templates
drwxrwxr-x 4 openedx openedx 4.0K May 23 04:14 universal
openedx@272f23c7aafc:~/edx-platform$ ls -lh /openedx/config/universal/cms/
total 8.0K
-rw-rw-r-- 1 openedx openedx   0 May 23 04:14 __init__.py
-rw-rw-r-- 1 openedx openedx 798 May 23 04:14 development.py
-rw-rw-r-- 1 openedx openedx 933 May 23 04:14 production.py
```

**Comment by regisb** [comment]
Sorry, I'm new to docker image tagging. The image that was uploaded to dockerhub had a bug. Please run `make update` and try again, then close this issue if it solved your problem.

**Comment by macagua** [comment]
@regisb Don't worry also I am newbie with Docker, I still don't build any Docker image, for that I report you the issue.

I followed your instructions and it's work very well :-)

Really thanks for your quickly support for fix this issue.
