### ISSUE TITLE
Could not upload profile image on LMS and file on CMS

### ISSUE THREAD

**Issue by ctsdevteam** [regisb/openedx-docker#54]
Hi all, 

I've deployed on Ubuntu machine, the rest of LMS and CMS are working properly except the uploading file got problem, could anyone help me out please.

1. When I try to change my profile image on LMS, the log said file generated

> lms_1              | 2018-08-25 06:56:42,168 INFO 10 [openedx.core.djangoapps.profile_images.views] views.py:162 - Generated and uploaded images ['84e1c62c20974b5b2ad951d466e9f0fc_120.jpg', '84e1c62c20974b5b2ad951d466e9f0fc_50.jpg', '84e1c62c20974b5b2ad951d466e9f0fc_500.jpg', '84e1c62c20974b5b2ad951d466e9f0fc_30.jpg'] for user 2

But when I access the image http://domain.com/media/profile-images/84e1c62c20974b5b2ad951d466e9f0fc_500.jpg?v=1535180202 I got **404 Not Found**

2. Another problem is on CMS
- Whenever I go to _Course > Content > File & Upload_ I'm getting this error on the log

> cms_1              | Traceback (most recent call last):
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
cms_1              |     response = get_response(request)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
cms_1              |     response = self._get_response(request)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
cms_1              |     response = self.process_exception_by_middleware(e, request)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
cms_1              |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
cms_1              |     return func(*args, **kwargs)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
cms_1              |     return view_func(request, *args, **kwargs)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
cms_1              |     response = view_func(request, *args, **kwargs)
cms_1              |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/assets.py", line 75, in assets_handler
cms_1              |     return _assets_json(request, course_key)
cms_1              |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/assets.py", line 146, in _assets_json
cms_1              |     assets, total_count = _get_assets_for_page(course_key, query_options)
cms_1              |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/assets.py", line 329, in _get_assets_for_page
cms_1              |     course_key, start=start, maxresults=page_size, sort=sort, filter_params=filter_params
cms_1              |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/contentstore/mongo.py", line 209, in get_all_content_for_course
cms_1              |     course_key, start=start, maxresults=maxresults, get_thumbnails=False, sort=sort, filter_params=filter_params
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/mongodb_proxy.py", line 53, in wrapper
cms_1              |     return func(*args, **kwargs)
cms_1              |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/contentstore/mongo.py", line 300, in _get_all_content_for_course
cms_1              |     items = self.fs_files.aggregate(pipeline_stages)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1819, in aggregate
cms_1              |     "aggregate", self.__name, **command_kwargs)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 440, in _command
cms_1              |     msg, allowable_errors)
cms_1              |   File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 213, in _check_command_response
cms_1              |     raise OperationFailure(msg % errmsg, code, response)
cms_1              | OperationFailure: command SON([('aggregate', u'fs.files'), ('pipeline', [{'$match': SON([('content_son.tag', 'c4x'), ('content_son.org', u'OpenEDX'), ('content_son.course', u'AI101'), ('content_son.category', 'asset'), ('content_son.run', u'2018')])}, {'$sort': {u'uploadDate': -1}}, {'$group': {'count': {'$sum': 1}, '_id': None, 'results': {'$push': '$$ROOT'}}}, {'$project': {'count': 1, 'results': {'$slice': ['$results', 0, 50]}}}])]) on namespace openedx.$cmd failed: exception: invalid operator '$slice'

- When I try to upload the file it show successfully uploaded and I also can access the image on browser, but file list doesn't show up 
![image](https://user-images.githubusercontent.com/42690973/44615923-98037600-a86f-11e8-97b4-47828f7293b0.png)

**Comment by regisb** [comment]
Hi @ctsdevteam,
Thanks for reporting these issues! I'll try to find time to investigate this.

**Comment by ctsdevteam** [comment]
Hi @regisb,

Thanks a lot for replying on this matter. I'm not sure if below is the problem and also I really don't know how to fix it.

When I try to upload the profile image, all the images uploaded to docker **openedx-docker_lms_1** instead of **openedx-docker_nginx_1**

![image](https://user-images.githubusercontent.com/42690973/44653811-ed7b8680-aa19-11e8-96cd-fc5586c49cff.png)

And also take a look on this **nginx config file** https://github.com/regisb/openedx-docker/blob/master/config/nginx/templates/lms.conf.templ and saw the the location for media is actually on nginx

![image](https://user-images.githubusercontent.com/42690973/44654017-83171600-aa1a-11e8-9958-b4637008cba2.png)

**Comment by regisb** [comment]
@ctsdevteam,
Thanks again for your thorough reporting. Issue 1 was related to incorrect PROFILE_IMAGE_BACKEND setting. Issue 2 was due to an older version of mongodb -- hawthorn now requires a more recent version.

FYI, the media files served by nginx are found thanks to a docker volume: the static assets collected by the lms are stored in `./data/lms`. This folder is then shared with the nginx container through the [docker-compose configuration](https://github.com/regisb/openedx-docker/blob/master/docker-compose.yml#L48).

**Comment by ctsdevteam** [comment]
Hi @regisb,

Thank you for letting me know about the shared between these 2 dockers, but could you please help me out as I really don't understand this.

The **nginx config file** is pointing to /openedx/data/lms/uploads on LMS docker. But how come the user profile image uploaded to this /edx/var/edxapp/media/profile-images on LMS docker as below picture.

https://user-images.githubusercontent.com/42690973/44653811-ed7b8680-aa19-11e8-96cd-fc5586c49cff.png

And by the way, you also mentioned about "_incorrect PROFILE_IMAGE_BACKEND setting_", can you let me know where I can change that config please

**Comment by ctsdevteam** [comment]
Thank you for your help @regisb.
