### ISSUE TITLE
'Settings' object has no attribute 'LMS_SEGMENT_KEY'

### ISSUE THREAD

**Issue by gmsk19** [regisb/openedx-docker#59]
I have trying to build ginkgo using the project. I have been able to build developer builds for a while now. I tried to build for production deployment.  I get the following error:
I actually do not need the LMS, when i do not run LMS, then the server runs fine but not able to access the server at the given domain name (Have the A record configured) or IP address of server machine.

lms_worker_1     |
lms_worker_1     | Traceback (most recent call last):
lms_worker_1     |   File "/openedx/edx-platform/manage.py", line 112, in <module>
lms_worker_1     |     startup.run()
lms_worker_1     |   File "/openedx/edx-platform/lms/startup.py", line 62, in run
lms_worker_1     |     if settings.LMS_SEGMENT_KEY:
lms_worker_1     |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in __getattr__
lms_worker_1     |     return getattr(self._wrapped, name)
lms_worker_1     | AttributeError: 'Settings' object has no attribute 'LMS_SEGMENT_KEY'

With regards,
Shashi Kiran G M

**Comment by regisb** [comment]
Hi @gmsk19!
I don't understand: what command are you running? are you on branch release/ginkgo of openedx-docker? (you should)

**Comment by gmsk19** [comment]
Hi @regisb 
i am running make up. I shall go to branch release/ginkgo as you have pointed and will revert. Thanks.
