### ISSUE TITLE
error: [Errno 111] Connection refused when sending registration email

### ISSUE THREAD

**Issue by natea** [regisb/openedx-docker#6]
I can see the logs for the `openedxdocker_lms` container that it's attempting to send the registration emails, but it's getting a connection refused:

```
2018-02-16 23:32:23,197 INFO 1 [celery.worker.consumer] consumer.py:479 - Connected to amqp://guest:**@rabbitmq:5672//
2018-02-16 23:32:23,209 INFO 1 [celery.worker.consumer] consumer.py:567 - mingle: searching for neighbors
2018-02-16 23:32:24,221 INFO 1 [celery.worker.consumer] consumer.py:585 - mingle: all alone
2018-02-16 23:32:24,243 WARNING 1 [celery.redirected] log.py:282 - celery@edx.lms.core.default.%8fffbfe952ed ready.
2018-02-16 23:56:32,936 INFO 1 [celery.worker.strategy] strategy.py:55 - Received task: student.tasks.send_activation_email[e629b21c-b3f6-41d7-a851-3405a704472c]
2018-02-16 23:56:32,998 ERROR 120 [edx.celery.task] tasks.py:48 - Unable to send activation email to user from "registration@example.com" to "nate@appsembler.com"
Traceback (most recent call last):
  File "/openedx/edx-platform/common/djangoapps/student/tasks.py", line 23, in send_activation_email
    mail.send_mail(subject, message, from_address, [dest_addr], fail_silently=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
2018-02-16 23:56:33,026 ERROR 1 [celery.worker.job] log.py:282 - Task student.tasks.send_activation_email[e629b21c-b3f6-41d7-a851-3405a704472c] raised unexpected: Exception()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/openedx/edx-platform/common/djangoapps/student/tasks.py", line 50, in send_activation_email
    raise Exception
Exception
```

When I look at the logs of the `openedxdocker_smtp` container, it appears to be listening on port 25.

```
+ sed -ri '
s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:25 ; [::0]:25'\''/;
s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
s/^#?(dc_relay_nets)=.*/\1='\''172.18.0.3\/16'\''/;
s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
' /etc/exim4/update-exim4.conf.conf
+ update-exim4.conf -v
using non-split configuration scheme from /etc/exim4/exim4.conf.template
    1 LOG: MAIN
    1   exim 4.84_2 daemon started: pid=1, -q15m, listening for SMTP on port 25 (IPv6 and IPv4)
```

Any idea why it's unable to connect to the SMTP container?

**Comment by regisb** [comment]
I haven't tested the fix but I'm pretty sure the error is caused by a port misconfiguration. Please try again after re-configuring the images (`./configure --silent`).

**Comment by natea** [comment]
After running `./configure --silent` and re-building the images, now the SMTP works and I don't get an error message. Although the email message went into my Gmail spam folder. ;)

**Comment by natea** [comment]
I'm getting some other SMTP errors now, even after running `./configure --silent` and rebuilding the images again.

```
smtp_1        |   279 LOG: MAIN
smtp_1        |   279   <= registration@example.com H=openedxdocker_cms_worker_1.openedxdocker_default (2e0067ba16e8) [172.18.0.11] P=esmtp S=755 id=20180316045055.122.75257@2e0067ba16e8
smtp_1        |   279 LOG: smtp_connection MAIN
smtp_1        |   279   SMTP connection from openedxdocker_cms_worker_1.openedxdocker_default (2e0067ba16e8) [172.18.0.11] closed by QUIT
smtp_1        |   280 Exim version 4.84_2 uid=104 gid=108 pid=280 D=40001
cms_worker_1  | [2018-03-16 04:50:55,777: INFO/Worker-2] cms_user_tasks.tasks.send_task_complete_email[ae34f582-498f-427d-acc4-516687e30e87]: Task complete email has been sent to User natejaune@gmail.com
smtp_1        | Berkeley DB: Berkeley DB 5.3.28: (September  9, 2013)
smtp_1        | Support for: crypteq iconv() IPv6 GnuTLS move_frozen_messages DKIM PRDR OCSP
smtp_1        | Lookups (built-in): lsearch wildlsearch nwildlsearch iplsearch cdb dbm dbmjz dbmnz dnsdb dsearch nis nis0 passwd
smtp_1        | Authenticators: cram_md5 plaintext
smtp_1        | Routers: accept dnslookup ipliteral manualroute queryprogram redirect
smtp_1        | Transports: appendfile/maildir/mailstore autoreply lmtp pipe smtp
smtp_1        | Fixed never_users: 0
smtp_1        | Size of off_t: 8
cms_worker_1  | [2018-03-16 04:50:55,785: INFO/MainProcess] Task cms_user_tasks.tasks.send_task_complete_email[ae34f582-498f-427d-acc4-516687e30e87] succeeded in 0.0893751849653s: None
smtp_1        |   280 delivering 1ewhKR-00004V-OP
smtp_1        |   280 R: dnslookup for natejaune@gmail.com
smtp_1        |   282 T: remote_smtp for natejaune@gmail.com
smtp_1        |   282 Connecting to gmail-smtp-in.l.google.com [2607:f8b0:400e:c03::1a]:25 ... failed: Cannot assign requested address
smtp_1        |   282 LOG: MAIN
smtp_1        |   282   gmail-smtp-in.l.google.com [2607:f8b0:400e:c03::1a] Cannot assign requested address
nginx_1       | 172.18.0.1 - - [16/Mar/2018:04:50:58 +0000] "GET /import_status/course-v1:Appsembler+ITP101+2018_Winter/course.ZKpzeN.tar.gz HTTP/1.1" 200 35 "http://studio.myopenedx.com/import/course-v1:Appsembler+ITP101+2018_Winter" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "-"
cms_worker_1  | [2018-03-16 04:51:04,321: INFO/Worker-4] BlockStructure: Added to cache; <openedx.core.djangoapps.content.block_structure.store.StubModel object at 0x7f43ca248e10>, size: 1430
cms_worker_1  | [2018-03-16 04:51:04,323: INFO/MainProcess] Task openedx.core.djangoapps.content.block_structure.tasks.update_course_in_cache_v2[e2a9c09a-744e-4cfb-8976-8ddc53845df0] succeeded in 0.0518249629531s: None
smtp_1        |   282 Connecting to gmail-smtp-in.l.google.com [74.125.197.27]:25 ... failed: Connection refused
smtp_1        |   282 LOG: MAIN
smtp_1        |   282   gmail-smtp-in.l.google.com [74.125.197.27] Connection refused
smtp_1        |   282 Connecting to alt1.gmail-smtp-in.l.google.com [2607:f8b0:4001:c15::1a]:25 ... failed: Cannot assign requested address
smtp_1        |   282 LOG: MAIN
smtp_1        |   282   alt1.gmail-smtp-in.l.google.com [2607:f8b0:4001:c15::1a] Cannot assign requested address
```

**Comment by regisb** [comment]
Hi Nate! If I understand correctly, you configured Open edX to use Gmail as your SMTP server, right? I believe you may not use Gmail to send emails from an address that is not associated to your account. The adress that you are using is `registration@example.com`.

Please try setting `DEFAULT_FROM_EMAIL = 'natejaune@gmail.com'` in `edxapp/config/production_common.py`. Then build the image again and try creating another account. If it works, then it means I was right :)

I realise that the Open edX docker images do not override the default addresses from which emails are sent:

```
DEFAULT_FROM_EMAIL = 'registration@example.com'
DEFAULT_FEEDBACK_EMAIL = 'feedback@example.com'
SERVER_EMAIL = 'devops@example.com'
TECH_SUPPORT_EMAIL = 'technical@example.com'
CONTACT_EMAIL = 'info@example.com'
BUGS_EMAIL = 'bugs@example.com'
UNIVERSITY_EMAIL = 'university@example.com'
PRESS_EMAIL = 'press@example.com'
PAYMENT_SUPPORT_EMAIL = 'payment@example.com'
BULK_EMAIL_DEFAULT_FROM_EMAIL = 'no-reply@example.com'
API_ACCESS_MANAGER_EMAIL = 'api-access@example.com'
API_ACCESS_FROM_EMAIL = 'api-requests@example.com'
```

We should fix that.
