### ISSUE TITLE
course export/import

### ISSUE THREAD

**Issue by paracamplus** [regisb/openedx-docker#72]
Hi,

I installed openedx-docker within a VM with Debian9 + docker + docker-compose.
'make all' with a non-root user worked fine (thanks!), lms and cms apparently run smoothly when browsed. The whole installation uses 10G on a 30G disk. 

Problem: exporting a course does not work, the 'exporting' phase (the one after the "preparing' phase) never ends. 

Within the openedx-docker_cms_1 container, the command `python ./manage.py cms export -v3 course-v1:CodeGradX+test+test1 /tmp/` fails with `pymongo.errors.ConnectionFailure: [Errno 111] Connection refused`

Conversely, the import facility does not work either, it never ends the "unpacking" phase. Fortunately,
within the openedx-docker_cms_1 container, the command `python ./manage.py cms import ../data /tmp/coursetest` works.

Any idea ?

## Steps to reproduce

Include the exact command that you are running and that is causing an error. In case of a web error, include the URL of the page that is causing the error.

```sh
root@1dd9c4382002:/openedx/edx-platform# python ./manage.py cms export -v3 course-v1:CodeGradX+test+test1 /tmp/ 
Traceback (most recent call last):
  File "./manage.py", line 121, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/openedx/edx-platform/cms/djangoapps/contentstore/management/commands/export.py", line 36, in handle
    if not modulestore().get_course(course_key):
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 321, in modulestore
    settings.MODULESTORE['default'].get('OPTIONS', {})
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 303, in create_modulestore_instance
    **_options
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 176, in __init__
    signal_handler=signal_handler,
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 303, in create_modulestore_instance
    **_options
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 707, in __init__
    self.db_connection = MongoConnection(**doc_store_config)
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py", line 300, in __init__
    retry_wait_time=retry_wait_time, **kwargs
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/mongo_utils.py", line 50, in connect_to_mongodb
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 425, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused
```

## Unexpected behavior

Include the full, exact output from the command that is causing your issue. Also include relevant error logs; for instance, to debug the LMS take a look at the files in `data/lms/logs`.

data/cms/logs is empty

but docker-compose logs shows:

```sh
cms_1            | 2018-09-30 13:30:28,935 INFO 751 [tracking] logger.py:50 - {"username": "edxstaff", "event_type": "/export_status/course-v1:CodeGradX+test+test1", "ip": "192.168.122.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36", "host": "moocjsedxstudio", "referer": "https://moocjsedxstudio/export/course-v1:CodeGradX+test+test1", "accept_language": "fr,en-US;q=0.9,en;q=0.8", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 3, "org_id": "", "course_id": "", "path": "/export_status/course-v1:CodeGradX+test+test1"}, "time": "2018-09-30T13:30:28.935011+00:00", "page": null}
nginx_1          | 192.168.122.1 - - [30/Sep/2018:13:30:28 +0000] "GET /export_status/course-v1:CodeGradX+test+test1 HTTP/1.0" 200 23 "https://moocjsedxstudio/export/course-v1:CodeGradX+test+test1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "88.190.172.74"
cms_1            | 2018-09-30 13:30:29,029 INFO 751 [tracking] logger.py:50 - {"username": "edxstaff", "event_type": "/course/course-v1:CodeGradX+test+test1", "ip": "192.168.122.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36", "host": "moocjsedxstudio", "referer": "https://moocjsedxstudio/export/course-v1:CodeGradX+test+test1", "accept_language": "fr,en-US;q=0.9,en;q=0.8", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 3, "org_id": "", "course_id": "", "path": "/course/course-v1:CodeGradX+test+test1"}, "time": "2018-09-30T13:30:29.029072+00:00", "page": null}
mongodb_1        | 2018-09-30T13:30:29.053+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.10:46114 #29 (4 connections now open)
mongodb_1        | 2018-09-30T13:30:29.093+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.10:46116 #30 (5 connections now open)
mongodb_1        | 2018-09-30T13:30:29.099+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.10:46118 #31 (6 connections now open)
```

## Additional info (IMPORTANT)

Include the output of the `make info` command.

```sh
:/opt/openedx-docker$ make info
uname -a
Linux ddre 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
-------------------------
git rev-parse HEAD
fb36eb2d4eb19fc6865f890755823fc416be907d
-------------------------
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
-------------------------
docker-compose --version
docker-compose version 1.22.0, build f46880fe
-------------------------
echo $EDX_PLATFORM_PATH

echo $EDX_PLATFORM_SETTINGS
```

**Comment by regisb** [comment]
Good catch @paracamplus! This was an indirect consequence of a weird syntax bug in the docker-compose.yml file. I managed to reproduce the bug and can confirm that the export now works, both from the command line and the CMS frontend. Note that you may have to tell the CMS that the export task is not pending. You will most certainly have to clear your session cookies (strange, but true https://github.com/edx/edx-platform/blob/open-release/hawthorn.master/cms/djangoapps/contentstore/views/import_export.py#L367) and you *may* have to remove a "User Task Status" entry in the  admin: http://studio.localhost/admin/user_tasks/usertaskstatus/
