### ISSUE TITLE
paver update_assets not working with developer settings

### ISSUE THREAD

**Issue by bmedx** [regisb/openedx-docker#73]
Following the developer instructions on a fresh pull of master I ran into an error trying to generate static assets. I believe that I did not run into this issue with production settings. I was able to resolve it by updating the command to skip Python uninstalls:

`NO_PYTHON_UNINSTALL=1 paver update_assets lms --settings=universal.development`

## Steps to reproduce

1. git clone https://github.com/regisb/openedx-docker.git
2. cd openedx-docker/
3. make all
4. export EDX_PLATFORM_SETTINGS=universal.development
5. make lms
6. paver update_assets lms --settings=universal.development

## Unexpected behavior
Typical output, followed by:

```---> pavelib.prereqs.uninstall_python_packages
pip freeze
pip uninstall --disable-pip-version-check -y edxval
Uninstalling edxval-0.1.16:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 326, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 747, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/edxval-0.1.16.dist-info/INSTALLER'
```

## Additional info (IMPORTANT)

```
uname -a
Darwin C02RD35PG8WM.tld 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
-------------------------
git rev-parse HEAD
fb36eb2d4eb19fc6865f890755823fc416be907d
-------------------------
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
-------------------------
docker-compose --version
docker-compose version 1.21.2, build a133471
-------------------------
echo $EDX_PLATFORM_PATH

echo $EDX_PLATFORM_SETTINGS
universal.development
```

**Comment by regisb** [comment]
Thanks for reporting this @bmedx! Indeed, we don't need to manually uninstall packages. This will be solved in the last version of the openedx image where the NO_PYTHON_UNINSTALL environment variable will be defined globally.
