### ISSUE TITLE
NotImplementedError: edX Studio doesn't support third-party xblock handler urls

### ISSUE THREAD

**Issue by natea** [regisb/openedx-docker#8]
After attempting to import the demo course (see #7), I get this error when running `make up`:

```
cms_worker_1  | [2018-02-17 00:08:19,782: ERROR/Worker-3] BlockStructure: update_course_in_cache_v2 encountered unknown error in course course-v1:edX+DemoX+Demo_Course, task_id ff0429d7-8e9e-4407-a1f5-246a35af68f8. Retry #0
cms_worker_1  | Traceback (most recent call last):
cms_worker_1  |   File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/tasks.py", line 101, in _call_and_retry_if_needed
cms_worker_1  |     api_method(course_key)
cms_worker_1  |   File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/api.py", line 29, in update_course_in_cache
cms_worker_1  |     return get_block_structure_manager(course_key).update_collected_if_needed()
cms_worker_1  |   File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 115, in update_collected_if_needed
cms_worker_1  |     self._update_collected()
cms_worker_1  |   File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 127, in _update_collected
cms_worker_1  |     BlockStructureTransformers.collect(block_structure)
cms_worker_1  |   File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/transformers.py", line 80, in collect
cms_worker_1  |     transformer.collect(block_structure)
cms_worker_1  |   File "/openedx/edx-platform/lms/djangoapps/course_api/blocks/transformers/blocks_api.py", line 51, in collect
cms_worker_1  |     StudentViewTransformer.collect(block_structure)
cms_worker_1  |   File "/openedx/edx-platform/lms/djangoapps/course_api/blocks/transformers/student_view.py", line 63, in collect
cms_worker_1  |     student_view_data = block.student_view_data()
cms_worker_1  |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/video_module/video_module.py", line 984, in student_view_data
cms_worker_1  |     for lang in self.available_translations(transcripts_info, verify_assets=False)
cms_worker_1  |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/video_module/video_module.py", line 984, in <dictcomp>
cms_worker_1  |     for lang in self.available_translations(transcripts_info, verify_assets=False)
cms_worker_1  |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1480, in handler_url
cms_worker_1  |     return descriptor_global_handler_url(block, handler_name, suffix, query, thirdparty)
cms_worker_1  |   File "/openedx/edx-platform/cms/lib/xblock/runtime.py", line 14, in handler_url
cms_worker_1  |     raise NotImplementedError("edX Studio doesn't support third-party xblock handler urls")
cms_worker_1  | NotImplementedError: edX Studio doesn't support third-party xblock handler urls
```

**Comment by regisb** [comment]
I believe this error is unrelated to this project: it just means that the studio cannot load transcripts from an external source. The error can be ignored.

Please feel free to re-open this issue if you do not observe the same error in a native open edx install.
