### ISSUE TITLE
Trouble with capa

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#85]
Today I'm having trouble with the capa module.  To replicate this trouble: 
1. login to the 6.004.1x test course I sent you.
2. Go to LE7.1 and answer the first question with L, and the second with 2*T (the correct answers).
3. Then you should get the error below:

```
Staff debug info: Traceback (most recent call last): 
File "/openedx/edx-platform/common/lib/xmodule/xmodule/capa_base.py", line 1219, in submit_problem 
  correct_map = self.lcp.grade_answers(answers) 
File "/openedx/edx-platform/common/lib/capa/capa/capa_problem.py", line 401, in grade_answers 
  new_cmap = self.get_grade_from_current_answers(answers) 
File "/openedx/edx-platform/common/lib/capa/capa/capa_problem.py", line 459, in get_grade_from_current_answers 
  results = responder.evaluate_answers(self.student_answers, oldcmap) 
File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 309, in evaluate_answers 
  new_cmap = self.get_score(student_answers) 
File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 3086, in get_score 
  self.samples 
File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 3186, in check_formula 
  student_result = self.tupleize_answers(given, var_dict_list) 
File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 3113, in tupleize_answers 
  _("Invalid input: {bad_input} not permitted in answer.").format(bad_input=text_type(err)) StudentInputError: Invalid input: T not permitted in answer.
```

The logs show:

```
nginx_1          | 172.19.0.1 - - [05/Nov/2018:15:57:05 +0000] "POST /event HTTP/1.1" 204 0 "http://studio.edx.fweb.wallawalla.edu/container/block-v1:wallawalla+engr354+2018+type@vertical+block@c12s1v3" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "174.127.180.10"
cms_1            | 2018-11-05 15:57:05,148 INFO 238 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/preview/xblock/block-v1:wallawalla+engr354+2018+type@problem+block@performance_performance_FA11_Q2_P1D_FingerExercise/handler/xmodule_handler/problem_check", "ip": "172.19.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/container/block-v1:wallawalla+engr354+2018+type@vertical+block@c12s1v3", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {\"input_performance_performance_FA11_Q2_P1D_FingerExercise_3_1\": [\"T*2\"], \"input_performance_performance_FA11_Q2_P1D_FingerExercise_2_1\": [\"L\"]}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/preview/xblock/block-v1:wallawalla+engr354+2018+type@problem+block@performance_performance_FA11_Q2_P1D_FingerExercise/handler/xmodule_handler/problem_check"}, "time": "2018-11-05T15:57:05.147778+00:00", "page": null}
cms_1            | 2018-11-05 15:57:05,196 WARNING 238 [codejail] safe_exec.py:248 - Using codejail/safe_exec.py:not_safe_exec for performance_performance_FA11_Q2_P1D_FingerExercise
cms_1            | 2018-11-05 15:57:05,212 WARNING 238 [edx.courseware] capa_base.py:1230 - StudentInputError in capa_module:problem_check
cms_1            | Traceback (most recent call last):
cms_1            |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/capa_base.py", line 1219, in submit_problem
cms_1            |     correct_map = self.lcp.grade_answers(answers)
cms_1            |   File "/openedx/edx-platform/common/lib/capa/capa/capa_problem.py", line 401, in grade_answers
cms_1            |     new_cmap = self.get_grade_from_current_answers(answers)
cms_1            |   File "/openedx/edx-platform/common/lib/capa/capa/capa_problem.py", line 459, in get_grade_from_current_answers
cms_1            |     results = responder.evaluate_answers(self.student_answers, oldcmap)
cms_1            |   File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 309, in evaluate_answers
cms_1            |     new_cmap = self.get_score(student_answers)
cms_1            |   File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 3086, in get_score
cms_1            |     self.samples
cms_1            |   File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 3186, in check_formula
cms_1            |     student_result = self.tupleize_answers(given, var_dict_list)
cms_1            |   File "/openedx/edx-platform/common/lib/capa/capa/responsetypes.py", line 3113, in tupleize_answers
cms_1            |     _("Invalid input: {bad_input} not permitted in answer.").format(bad_input=text_type(err))
cms_1            | StudentInputError: Invalid input: T not permitted in answer.
```

**Comment by frohro** [comment]
Stopping and restarting the system did nothing to remove the problem.

**Comment by regisb** [comment]
First of all, I need to make sure that this error is not an artefact of the course export script. Are you doing this on a .tar.gz file directly exported from edx.org?

**Comment by frohro** [comment]
No, this is the same class that was exported on an unknown script.  Should I import it to edunext, and export it again, or should I ask for the MIT professor to export it from edX if he can, or something else?

**Comment by frohro** [comment]
... and if I substitute the question line from the earlier question in its place like so:
    <formularesponse answer="$latency_1" samples="L, T @-1,-1:1,1#10" type="ci"><responseparam default="0.00001" type="tolerance"/><formulaequationinput inline="1" label="Enter the equation" size="40"/></formularesponse>
    <script type="loncapa/python">
latency_1 = "L"
    </script>
It works just fine.

**Comment by frohro** [comment]
Okay, this was a problem with the problem.  I fixed it by replacing an L with a T where it was necessary.  If anyone is interested, it now looks like this:

    <formularesponse answer="$throughput_1" samples="T, T @-1,-1:1,1#10" type="ci"><responseparam default="0.00001" type="tolerance"/><formulaequationinput inline="1" label="Enter the equation" size="40"/></formularesponse>
    <script type="loncapa/python">
throughput_1 = "2*T"
    </script>

**Comment by frohro** [comment]
One more comment on this in case someone else cares:  it turns out that the spaces were the issue, not the L.  More on this can be found in the openedx docs [here](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/math_expression_input.html#attributes).

**Comment by regisb** [comment]
Awesome, thanks for debugging this!
